---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3

  integration-windows:
    needs: lint-unit
    runs-on: windows-latest
    strategy:
      matrix:
        os:
          - windows-2019
        suite:
          - default
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
